version: '3'

services:
  portfolio:
    container_name: portfolio
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8000:8000"

  db:
    container_name: postgres
    image: postgres
    # restart: always
    environment:
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
