version: '3.9'

services:
  portfolio:
    container_name: portfolio
    build: .
    command: python manage.py 
      runserver_plus 0.0.0.0:8000 
      --cert-file /code/portfolio.dev+4.pem
      --key-file /code/portfolio.dev+4-key.pem
      --nopin
    volumes:
      - ./portfolio:/code
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8000:8000"

  db:
    container_name: postgres
    image: postgres
    # restart: always
    environment:
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
