version: '3'

services:
  web:
    container_name: portfolio
    build: .
    command: gunicorn portfolio.wsgi --bind 0.0.0.0:8000 -w 5 -t 120 --log-level=debug
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./portfolio:/code
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - backend
    depends_on:
      - web

  db:
    container_name: postgres
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
